---
dependency:
  name: galaxy
driver:
  name: docker
lint: |
  set -e
  yamllint .
  ansible-lint
platforms:
  - name: Debian
    image: debian:11
  - name: Centos
    image: centos:8
provisioner:
  name: ansible
verifier:
  name: ansible
