---
- name: Prepare
  hosts: all
  tasks:
    - name: Update apt cache (on Debian).
      apt:
        update_cache: true
      when: ansible_os_family == 'Debian'

    - name: Enable ruby 2.6 (Centos 8)
      command: dnf module enable -y ruby:2.6
      when: ansible_os_family == 'RedHat'

    - name: Install prerequisites
      package:
        name:
          - git
          - ruby
